//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zest_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public asset()
        {
            this.asset_prices = new HashSet<asset_prices>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string symbol { get; set; }
        public string bloomberg_code { get; set; }
        public string ISIN { get; set; }
        public Nullable<double> precio_entrada { get; set; }
        public Nullable<double> precio_salida { get; set; }
        public Nullable<double> valoracion { get; set; }
        public Nullable<double> barrera { get; set; }
        public Nullable<System.DateTime> fecha_default { get; set; }
        public Nullable<int> note_id { get; set; }
        public string url_img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asset_prices> asset_prices { get; set; }
        public virtual note note { get; set; }
    }
}
