//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zest_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalog_items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catalog_items()
        {
            this.catalog_item_details = new HashSet<catalog_item_details>();
            this.interes_investor_catalogs = new HashSet<interes_investor_catalogs>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string estado { get; set; }
        public string codigo_nota { get; set; }
        public Nullable<System.DateTime> vencimiento { get; set; }
        public Nullable<double> inv_minima { get; set; }
        public string riesgo { get; set; }
        public string emisor { get; set; }
        public string barrera { get; set; }
        public string moneda { get; set; }
        public string adicional { get; set; }
        public string descripcion { get; set; }
        public string isin { get; set; }
        public string barrera_capital { get; set; }
        public string rentabilidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_item_details> catalog_item_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<interes_investor_catalogs> interes_investor_catalogs { get; set; }
    }
}
