//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zest_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalog_fund_items
    {
        public int id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string estado { get; set; }
        public string codigo_fondo { get; set; }
        public Nullable<double> inv_minima { get; set; }
        public string moneda { get; set; }
        public string gestor { get; set; }
        public string administrador { get; set; }
        public string auditor { get; set; }
        public string custodio { get; set; }
        public string riesgo { get; set; }
        public string descripcion { get; set; }
        public string nombre_archivo { get; set; }
    }
}
