//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zest_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public int id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string periodo { get; set; }
        public Nullable<System.DateTime> f_observacion { get; set; }
        public Nullable<System.DateTime> f_pago { get; set; }
        public Nullable<double> cupon { get; set; }
        public string autocall { get; set; }
        public Nullable<double> importe_bruto { get; set; }
        public Nullable<double> importe_retencion { get; set; }
        public Nullable<int> pago { get; set; }
        public Nullable<int> note_id { get; set; }
    
        public virtual note note { get; set; }
    }
}
