//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zest_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class interes_investors
    {
        public int id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string investor_code { get; set; }
        public string nota { get; set; }
        public string status { get; set; }
    }
}
