//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zest_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class interes_investors
    {
        public int id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string investor_code { get; set; }
        public string nota { get; set; }
        public string status { get; set; }
    }
}
