//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zest_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public int id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string estado { get; set; }
        public string titular { get; set; }
        public string tipo { get; set; }
        public string descripcion { get; set; }
        public string url_img { get; set; }
        public string tags { get; set; }
        public string nota_codigo { get; set; }
        public string web_mobile { get; set; }
        public string cta { get; set; }
    }
}
