//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zest_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class osp_crm_leads
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public osp_crm_leads()
        {
            this.osp_crm_interactions = new HashSet<osp_crm_interactions>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string estado { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string source { get; set; }
        public string status { get; set; }
        public Nullable<decimal> aum { get; set; }
        public string risk_profile { get; set; }
        public Nullable<int> onboarding_status { get; set; }
        public string email { get; set; }
        public Nullable<decimal> m_saving { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<osp_crm_interactions> osp_crm_interactions { get; set; }
    }
}
