//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zest_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rent_months
    {
        public int id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string periodo { get; set; }
        public string periodo_nombre { get; set; }
        public Nullable<double> rentabilidad { get; set; }
        public Nullable<int> portfolio_id { get; set; }
        public Nullable<double> usd_rentabilidad { get; set; }
        public Nullable<double> retencion { get; set; }
        public Nullable<double> dividendo { get; set; }
    
        public virtual portfolio portfolio { get; set; }
    }
}
