//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zest_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Investors = new HashSet<Investor>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateLastLogin { get; set; }
        public System.DateTime DatePasswordChange { get; set; }
        public string Login { get; set; }
        public bool AccessAllInvestors { get; set; }
        public int UserGroupId { get; set; }
        public Nullable<int> InvestorId { get; set; }
        public Nullable<int> DashboardId { get; set; }
        public string CultureName { get; set; }
        public string TwoFactorAuthSecret { get; set; }
        public bool IsBlocked { get; set; }
        public string IntegrationCode { get; set; }
        public bool EnableDarkMode { get; set; }
        public string ThousandSeparator { get; set; }
        public string DecimalSeparator { get; set; }
        public string DateFormat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Investor> Investors { get; set; }
        public virtual Investor Investor { get; set; }
    }
}
