//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zest_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_25k1k
    {
        public int id { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string title { get; set; }
        public string description { get; set; }
    }
}
