//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zest_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_events
    {
        public int id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string estado { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> event_date { get; set; }
        public Nullable<int> duracion { get; set; }
        public string h_min { get; set; }
        public string lugar { get; set; }
        public string url_img { get; set; }
        public Nullable<int> event_default { get; set; }
        public string cta { get; set; }
        public string url_img_banner { get; set; }
    }
}
